# Generated by Django 2.2.5 on 2021-05-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210505_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bank',
            new_name='bank_name',
        ),
    ]
