# Generated by Django 2.2.5 on 2021-05-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210505_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_holder',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Bank holder's name"),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Main address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mobile phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip code'),
        ),
    ]
